_group = {
  {
    group_size = 1,
    pattern = "S",
    opcodes = "MOVSS,",
    offsets = "0,",
    addresses = "0xaee,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 5,
    pattern = "LLLLS",
    opcodes = "MOV,CMP,MOV,MOV,ADD,",
    offsets = "-20,-40,-20,-48,-20,",
    addresses = "0xaf6,0xafb,0xaab,0xab8,0xaf2,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 28,
    accessed_memory_nooverlap = 20,
    accessed_memory_overlap = 8,
    span = 32,
    head = 0,
    unroll_factor = 1,
  },
}
